alias mv='mv -vi'
alias cp='cp -vi'
alias rm='rm -vi'
alias path='echo -e ${PATH//:/\\n}'
alias conda='mamba'
alias jlab='mamba activate jlab && jupyter lab && mamba deactivate jlab'
alias rmident="find . -type f -name '*.Identifier' -print -exec rm -If {} \;"
alias ma='mamba activate' 
alias md='mamba deactivate'
alias subseq='samtools faidx'
alias vim='nvim'
alias ll="eza -l --icons"
alias llt="eza -1 --icons --tree"
alias ls="eza --icons --grid"
alias p="python"
alias conf="nvim ~/.bashrc"
alias confa="nvim ~/.config/bash/.bash_aliases"
alias refresh="source ~/.bashrc"
alias cat="bat"
alias pyani="pyani-plus"
